# Generated by Django 5.1.6 on 2025-02-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=100)),
                ('Clave', models.CharField(max_length=50)),
                ('Datos2', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
