# Generated by Django 5.1.6 on 2025-03-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_centralsystem_customuser_machine_sensor_sensordata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='programador',
            name='Datos',
        ),
        migrations.RemoveField(
            model_name='programador',
            name='Datos2',
        ),
        migrations.AddField(
            model_name='machine',
            name='Current',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='Pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='Temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='Voltage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='programador',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='programador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
