# Generated by Django 5.1.6 on 2025-03-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_centralsystem_customuser_machine_sensor_sensordata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='programador',
            name='Datos',
        ),
        migrations.RemoveField(
            model_name='programador',
            name='Datos2',
        ),
        migrations.AddField(
            model_name='machine',
            name='gps',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='machine',
            name='predictivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programador',
            name='Email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='programador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Pressure', models.FloatField(default=0.0)),
                ('Current', models.FloatField(default=0.0)),
                ('Temperature', models.FloatField(default=0.0)),
                ('Voltage', models.FloatField(default=0.0)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='api.machine')),
            ],
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
