#Generated by Django 5.1.6 on 2025-03-18 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sensordata_sensor_remove_programador_datos_and_more'),
    ]

    operations = [
        # Primero, crea el campo 'maquina' como nullable
        migrations.AddField(
            model_name='registro',
            name='maquina',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='registros',
                to='api.machine',
            ),
        ),
        # Luego, modifica el campo 'maquina' si es necesario
        migrations.AlterField(
            model_name='registro',
            name='maquina',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='registros',
                to='api.machine',
            ),
        ),
    ]