# Generated by Django 5.1.6 on 2025-03-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sensordata_sensor_remove_programador_datos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programador',
            name='Email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
