# Generated by Django 5.1.6 on 2025-03-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_machine_name_alter_registro_maquina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='maquina',
            new_name='machine',
        ),
    ]
