# Generated by Django 5.1.6 on 2025-02-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programador',
            name='Datos',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
