# Generated by Django 5.1.6 on 2025-04-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sensordata_sensor_remove_programador_datos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chirpstack_id',
            field=models.CharField(default=1111, max_length=36),
            preserve_default=False,
        ),
    ]
