# Generated by Django 5.1.6 on 2025-04-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_chirpstack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chirpstack_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
