# Generated by Django 5.1.6 on 2025-04-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chirpstack_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
